#docker-compose.yml
version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    command: ["gunicorn", "--reload", "--bind", "0.0.0.0:8000", "--workers", "3", "main:app"]
